### ISSUE TITLE
Quarkus 3: Jakarta EE support for jackson-databind

### ISSUE THREAD

**Issue by sboeckelmann** [quarkiverse/quarkus-opensearch#74]
ObjectMapper has issues with missing javax.xml.bind packages

`2023-06-16 16:28:59,433 ERROR [io.qua.mut.run.MutinyInfrastructure] (vert.x-eventloop-thread-4) Mutiny had to drop the following exception: java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlElement
        at com.fasterxml.jackson.module.jaxb.JaxbAnnotationIntrospector.<init>(JaxbAnnotationIntrospector.java:137)
        at com.fasterxml.jackson.module.jaxb.JaxbAnnotationIntrospector.<init>(JaxbAnnotationIntrospector.java:124)
        at com.fasterxml.jackson.module.jaxb.JaxbAnnotationModule.setupModule(JaxbAnnotationModule.java:98)
        at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:879)
        at com.fasterxml.jackson.databind.ObjectMapper.registerModules(ObjectMapper.java:1081)
        at com.fasterxml.jackson.databind.ObjectMapper.findAndRegisterModules(ObjectMapper.java:1165)
        at io.quarkiverse.opensearch.client.runtime.OpenSearchTransportProducer.openSearchTransport(OpenSearchTransportProducer.java:37)`

**Comment by sboeckelmann** [comment]
Not an issue related to quarkus-opensearch. An incompatible module was added to the dependencies of the 3rd party project. 
Anyhow, tests have been adjusted to make sure that jackson modules are supported.
